[package]
name = "axum-learn"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.8", features = ["cors"] }
